### ISSUE TITLE
Please add sponsors logo to summit 2017 page

### ISSUE THREAD

**Issue by koalie** [w3c/publishing#5]
Hi @tanyeah 
Please add ASAP the sponsors logos to the Publishing Summit 2017 overview page.

Vital Source:
	• http://www.w3.org/2017/11/TPAC/VS_Logo_Hor.png (480x83 px)
SPI Global:
	• http://www.w3.org/2017/11/TPAC/spi-global-hires.jpg (6742x1980 px)
	• http://www.w3.org/2017/11/TPAC/spi-global.jpg (1042x306 px)

Thanks!

**Comment by tanyeah** [comment]
Done. 
Waiting for transparent SPi Global logo, will make the change when I receive it.

**Comment by koalie** [comment]
Thanks!
